### ISSUE TITLE
Robot speed is low and not adjustable when using MoveIt2

### ISSUE THREAD

**Issue by mehradmrt** [TechmanRobotInc/tmr_ros2#41]
I am using MoveIt2 interface to run the TM5 robot. Setting max_velocity_scaling_factor does not change the robot's speed. I have struggled with robot speed and don't know if the problem is coming from the robot driver packages or moveIt. Using the demo packages (no Moveit) the robot velocity is correctly set and executed. 

Will appreciate a solution or a possible workaround to temporarily resolve the issue. I am mainly working on the foxy version but also tested it on humble and ran into same issues.

 - Robot Device: [TM5]
 - Your OS and Version: [e.g. Ubuntu 20.04 and 22.04]
 - ROS insatll: [e.g. ROS2 Foxy and Humble]
 - MoveIt install: [e.g. MoveIt2 on Foxy and Humble]

**Comment by okvik** [comment]
When controling the robot with MoveIt you may want to set the TM project to always run at 100% speed, and then scale that for each planned motion using MoveIt interfaces like `setMaxVelocityScalingFactor()` .  I don't know whether it is possible to control the project speed externally using SVR or SCT interfaces, I haven't had a need to do it as our entire program is done using MoveIt.

**Comment by mehradmrt** [comment]
Thanks for your reply @okvik. I did so but still the robot speed does not increase. I developed my code using MoveItCpp and on top of the demo that was already available in the repo, as opposed to MoveGroup where the setMaxVelocityScalingFactor() is available.

**Comment by okvik** [comment]
I'm sure there's equivalent functionality for velocity scaling with MoveItCpp.

**Comment by MasterpieceNKA** [comment]
I edited my ```config/joint_limits.yaml``` file to include ```max_acceleration values``` eg.

```yaml
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: true
    max_acceleration: 13.0
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: true
    max_acceleration: 13.0
```

This stops MoveIt from assuming a default acceleration of 1.0 rad/s^2 for each joint. More explanations can be found here: https://github.com/ros-industrial/motoman/issues/345#issuecomment-662693188

I could not find the exact acceleration values for my TM12 cobot but 13.0 rad/s^2 improved the speeds. The cobot reached the max_velocity of 2.09 rad/s by the third waypoint when jogging joint_1 on its own. 

These are the results from doing a Z-axis motion of the TCP

<img width="1006" alt="Image" src="https://github.com/user-attachments/assets/58a5af85-e245-40e6-bf4e-e5f187631bab" />
